import './js/header';
import './js/mobile-menu';
import './js/themeToggle';
import './js/hero';
import './js/pagi';
import './js/widelySearch_slave';
import './js/seachcatalog';
import './js/loader';
import './js/modal_movie';
import './js/create-trends';
import './js/modal-team';
import './js/paginations';
import './js/hero-trailer';
import './js/scroll-up'