import './js/header';
import './js/mobile-menu';
import './js/themeToggle';
import './js/hero';
import './js/modal-empty';
import './js/modal_movie';
import './js/upcoming';
import './js/loader';
import './js/create-trends';
import './js/modal-team';
import './js/scroll-up'
